// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import "@vue/runtime-core";

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    ElButton: typeof import("element-plus/es")["ElButton"];
    ElCard: typeof import("element-plus/es")["ElCard"];
    ElConfigProvider: typeof import("element-plus/es")["ElConfigProvider"];
    ElDivider: typeof import("element-plus/es")["ElDivider"];
    ElForm: typeof import("element-plus/es")["ElForm"];
    ElFormItem: typeof import("element-plus/es")["ElFormItem"];
    ElInput: typeof import("element-plus/es")["ElInput"];
    ElMenu: typeof import("element-plus/es")["ElMenu"];
    ElMenuItem: typeof import("element-plus/es")["ElMenuItem"];
    ElOption: typeof import("element-plus/es")["ElOption"];
    ElSelect: typeof import("element-plus/es")["ElSelect"];
    ElTable: typeof import("element-plus/es")["ElTable"];
    ElTableColumn: typeof import("element-plus/es")["ElTableColumn"];
    Home: typeof import("./components/Home.vue")["default"];
  }
}

export {};
